apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapi
  template:
    metadata:
      labels:
        app: springbootapi
    spec:
      containers:
        - name: springbootapi
          image: pasanbhanu/springboot-sample-api-with-prometheus:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springbootapi-service
  labels:
    monitoring: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: springbootapi
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
